spring:
  application:
    name: cachegate
  datasource:
    url: jdbc:sqlite:/Users/saumyajha/Documents/projects/cachegate/cachegate.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always

  main:
    banner-mode: "off"

  ai:
    openai:
      api-key: ${GROQ_API_KEY}

    mcp:
      server:
        stdio: true
        name: cachegate
        version: 0.1.0

    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.6-flash
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: gemini-embedding-2

groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai/v1
  model: openai/gpt-oss-120b

openrouter:
  api-key: ${OPENROUTER_API_KEY}
  base-url: https://openrouter.ai/api/v1
  model: openrouter/free